# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  taskmanagerapi:
    image: taskmanagerapi
    build:
      context: .
      dockerfile: src/TaskManager.Api/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5000:5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Data Source=/app/database/TaskManager.db
      - JwtSettings__SecretKey=${SECRET_KEY_FOR_JWT}
    volumes:
      - ${SQLITE_DB_DIR_PATH}:/app/database