// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskManager.Api.Infrastructure;

#nullable disable

namespace TaskManager.Api.Migrations
{
    [DbContext(typeof(TaskManagerDbContext))]
    [Migration("20260421095023_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("TaskManager.Api.Domain.Entity.TaskEntity", b =>
                {
                    b.Property<string>("TaskGuid")
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskDeadline")
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskDescrition")
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskOwnerUserGuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskOwnerUserUserGuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TaskGuid");

                    b.HasIndex("TaskOwnerUserUserGuid");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("TaskManager.Api.Domain.Entity.UserEntity", b =>
                {
                    b.Property<string>("UserGuid")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserData")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserGuid");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TaskManager.Api.Domain.Entity.TaskEntity", b =>
                {
                    b.HasOne("TaskManager.Api.Domain.Entity.UserEntity", "TaskOwnerUser")
                        .WithMany()
                        .HasForeignKey("TaskOwnerUserUserGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskOwnerUser");
                });
#pragma warning restore 612, 618
        }
    }
}
